export const FITNESS_EVENTS = {
  WEIGHT_RECORDED: 'FITNESS_WEIGHT_RECORDED',
  MEAL_LOGGED: 'FITNESS_MEAL_LOGGED',
  WORKOUT_COMPLETED: 'FITNESS_WORKOUT_COMPLETED',
  DAILY_ENTRY_SAVED: 'FITNESS_DAILY_ENTRY_SAVED',
  MEASUREMENT_SAVED: 'FITNESS_MEASUREMENT_SAVED',
} as const
