// Core event names
export const CORE_EVENTS = {
  PROFILE_UPDATED: 'CORE_PROFILE_UPDATED',
  PLUGIN_ACTIVATED: 'CORE_PLUGIN_ACTIVATED',
  PLUGIN_DEACTIVATED: 'CORE_PLUGIN_DEACTIVATED',
  ONBOARDING_COMPLETED: 'CORE_ONBOARDING_COMPLETED',
  SETTINGS_UPDATED: 'CORE_SETTINGS_UPDATED',
} as const

export const GAMIFICATION_EVENTS = {
  POINTS_ADDED: 'GAMIFICATION_POINTS_ADDED',
  ACHIEVEMENT_UNLOCKED: 'GAMIFICATION_ACHIEVEMENT_UNLOCKED',
  LEVEL_UP: 'GAMIFICATION_LEVEL_UP',
} as const
