export const WORK_EVENTS = {
  TASK_CREATED: 'WORK_TASK_CREATED',
  TASK_UPDATED: 'WORK_TASK_UPDATED',
  TASK_COMPLETED: 'WORK_TASK_COMPLETED',
  TASK_DELETED: 'WORK_TASK_DELETED',
  TASK_BLOCKED: 'WORK_TASK_BLOCKED',
  TASK_STARTED: 'WORK_TASK_STARTED',
  TASK_SWITCHED: 'WORK_TASK_SWITCHED',
  TASK_MOVED: 'WORK_TASK_MOVED',
  FOCUS_STARTED: 'WORK_FOCUS_STARTED',
  FOCUS_COMPLETED: 'WORK_FOCUS_COMPLETED',
  FOCUS_INTERRUPTED: 'WORK_FOCUS_INTERRUPTED',
  NOTE_CREATED: 'WORK_NOTE_CREATED',
} as const
