export const KNOWLEDGE_EVENTS = {
  RESOURCE_CREATED: 'KNOWLEDGE_RESOURCE_CREATED',
  RESOURCE_UPDATED: 'KNOWLEDGE_RESOURCE_UPDATED',
  RESOURCE_DELETED: 'KNOWLEDGE_RESOURCE_DELETED',
  RESOURCE_STARTED: 'KNOWLEDGE_RESOURCE_STARTED',
  RESOURCE_FINISHED: 'KNOWLEDGE_RESOURCE_FINISHED',

  HIGHLIGHT_ADDED: 'KNOWLEDGE_HIGHLIGHT_ADDED',
  HIGHLIGHT_DELETED: 'KNOWLEDGE_HIGHLIGHT_DELETED',
  HIGHLIGHT_PROMOTED_TO_TASK: 'KNOWLEDGE_HIGHLIGHT_PROMOTED_TO_TASK',

  FLASHCARD_CREATED: 'KNOWLEDGE_FLASHCARD_CREATED',
  FLASHCARD_REVIEWED: 'KNOWLEDGE_FLASHCARD_REVIEWED',
  FLASHCARD_DELETED: 'KNOWLEDGE_FLASHCARD_DELETED',

  STUDY_SESSION_STARTED: 'KNOWLEDGE_STUDY_SESSION_STARTED',
  STUDY_SESSION_FINISHED: 'KNOWLEDGE_STUDY_SESSION_FINISHED',
} as const

export type KnowledgeEventName =
  typeof KNOWLEDGE_EVENTS[keyof typeof KNOWLEDGE_EVENTS]
