export const HABITS_EVENTS = {
  HABIT_CREATED: 'HABITS_HABIT_CREATED',
  HABIT_UPDATED: 'HABITS_HABIT_UPDATED',
  HABIT_ARCHIVED: 'HABITS_HABIT_ARCHIVED',
  HABIT_LOGGED: 'HABITS_HABIT_LOGGED',
  HABIT_UNLOGGED: 'HABITS_HABIT_UNLOGGED',
  HABIT_GOAL_MET: 'HABITS_HABIT_GOAL_MET',
  HABIT_STREAK_BROKEN: 'HABITS_HABIT_STREAK_BROKEN',
} as const

export type HabitsEventName = typeof HABITS_EVENTS[keyof typeof HABITS_EVENTS]
