export const GOALS_EVENTS = {
  GOAL_CREATED: 'GOALS_GOAL_CREATED',
  GOAL_UPDATED: 'GOALS_GOAL_UPDATED',
  GOAL_COMPLETED: 'GOALS_GOAL_COMPLETED',
  GOAL_ARCHIVED: 'GOALS_GOAL_ARCHIVED',
  KR_CREATED: 'GOALS_KR_CREATED',
  KR_UPDATED: 'GOALS_KR_UPDATED',
  KR_PROGRESS: 'GOALS_KR_PROGRESS',
  KR_COMPLETED: 'GOALS_KR_COMPLETED',
  KR_DELETED: 'GOALS_KR_DELETED',
  MILESTONE_ADDED: 'GOALS_MILESTONE_ADDED',
} as const

export type GoalsEventName = typeof GOALS_EVENTS[keyof typeof GOALS_EVENTS]
