export const TIME_EVENTS = {
  PROJECT_CREATED: 'TIME_PROJECT_CREATED',
  PROJECT_UPDATED: 'TIME_PROJECT_UPDATED',
  PROJECT_DELETED: 'TIME_PROJECT_DELETED',
  ENTRY_STARTED: 'TIME_ENTRY_STARTED',
  ENTRY_STOPPED: 'TIME_ENTRY_STOPPED',
  ENTRY_CREATED: 'TIME_ENTRY_CREATED',
  ENTRY_UPDATED: 'TIME_ENTRY_UPDATED',
  ENTRY_DELETED: 'TIME_ENTRY_DELETED',
} as const

export type TimeEventName = (typeof TIME_EVENTS)[keyof typeof TIME_EVENTS]
