export const JOURNAL_EVENTS = {
  ENTRY_CREATED: 'JOURNAL_ENTRY_CREATED',
  ENTRY_UPDATED: 'JOURNAL_ENTRY_UPDATED',
  ENTRY_DELETED: 'JOURNAL_ENTRY_DELETED',
  ENTRY_PINNED: 'JOURNAL_ENTRY_PINNED',
  MOOD_LOGGED: 'JOURNAL_MOOD_LOGGED',
} as const

export type JournalEventName = typeof JOURNAL_EVENTS[keyof typeof JOURNAL_EVENTS]
