export const FINANCE_EVENTS = {
  ACCOUNT_CREATED: 'FINANCE_ACCOUNT_CREATED',
  ACCOUNT_UPDATED: 'FINANCE_ACCOUNT_UPDATED',
  ACCOUNT_ARCHIVED: 'FINANCE_ACCOUNT_ARCHIVED',
  CATEGORY_CREATED: 'FINANCE_CATEGORY_CREATED',
  CATEGORY_UPDATED: 'FINANCE_CATEGORY_UPDATED',
  CATEGORY_DELETED: 'FINANCE_CATEGORY_DELETED',
  TRANSACTION_CREATED: 'FINANCE_TRANSACTION_CREATED',
  TRANSACTION_UPDATED: 'FINANCE_TRANSACTION_UPDATED',
  TRANSACTION_DELETED: 'FINANCE_TRANSACTION_DELETED',
  TRANSFER_CREATED: 'FINANCE_TRANSFER_CREATED',
  RECURRING_CREATED: 'FINANCE_RECURRING_CREATED',
  RECURRING_UPDATED: 'FINANCE_RECURRING_UPDATED',
  RECURRING_MATERIALIZED: 'FINANCE_RECURRING_MATERIALIZED',
  BUDGET_CREATED: 'FINANCE_BUDGET_CREATED',
  BUDGET_UPDATED: 'FINANCE_BUDGET_UPDATED',
  BUDGET_DELETED: 'FINANCE_BUDGET_DELETED',
  ANOMALY_DETECTED: 'FINANCE_ANOMALY_DETECTED',
} as const

export type FinanceEventName = typeof FINANCE_EVENTS[keyof typeof FINANCE_EVENTS]
